# Generated by Django 5.2.6 on 2025-09-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_idioma', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
