# Generated by Django 5.2.6 on 2025-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.IntegerField(choices=[(1, 'superusuario'), (2, 'administrador'), (3, 'invitado'), (4, 'profesor'), (5, 'alumno')], default=5)),
                ('contrasena', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
